[package]
name = "herodotus_eth_starknet"
version = "0.1.0"
authors = ["Herodotus Dev"]

[[target.starknet-contract]]
sierra = true
casm = true

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.6.3"
cairo_lib = { git = "https://github.com/feltroidprime/cairo-lib.git", rev="eaeecf3"}
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }
alexandria_merkle_tree = {git = "https://github.com/keep-starknet-strange/alexandria.git", rev="fe337ab"}


[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.21.0" }


[tool.snforge]
exit_first = true

[tool.hints]
definitions = "hints/service.proto" # path to service definitions
# Default profile
[tool.sncast]
account = "herodotus"
network = "testnet"
url = "https://starknet-sepolia.public.blastapi.io"
